coverage:
  ignore:
    - "internal/**/*"
    - "examples/**/*"
    - "kbuilder/*"
    - "kstructs/*"
  status:
    project:
      default:
        # ignore errors from changes in coverage, this raises false negatives
        # for code refactors, and I do many refactors, so I don't want this.
        if_ci_failed: ignore
