coverage:
  ignore:
    - "internal/**/*"
    - "examples/**/*"
    - "kbuilder/*"
    - "kstructs/*"
  status:
    changes:
      default:
        threshold: 2%
        # ignore errors from changes, this raises false negatives for
        # code refactors, and I do many refactors, so I don't want this.
        #if_ci_failed: ignore
