name: CI

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      docker-in-docker:
        image: docker:dind
    steps:
      - uses: actions/checkout@v2
      - name: Run linters
        run: go vet ./...
      - name: Run tests
        run: go test ./...
